name: "Cache Node Modules"
description: "Caches node_modules for faster installs"

outputs:
  cache-hit:
    description: "Whether the cache was hit or not"
    value: ${{ steps.cache-node-modules.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('yarn.lock') }}
