version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  test: # this can be any name you choose
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn ci
      - run:
          command: PLAYWRIGHT_BROWSERS_PATH=/node_modules/playwright-browsers yarn add playwright-chromium@1.11.1
          name: Install playwright deps
      - run:
          command: PLAYWRIGHT_BROWSERS_PATH=/node_modules/playwright-browsers yarn test
          name: Run tests
      - persist_to_workspace: # cache stuff
          root: ~/project
          paths:
            - .
workflows:
  version: 2
  test:
    jobs:
      - test
