version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  run-test:
    docker:
      - image: cimg/node:18.16.0
        environment:
          DATABASE_URL: postgresql://user@localhost/db
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: db
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    parallelism: 4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          key: playwright-{{ checksum "yarn.lock" }}
      - run: npx playwright install --with-deps
      - save_cache:
          key: playwright-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/ms-playwright
      - run:
          name: Wait for db
          command: |
            for i in {1..60}; do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Apply database migrations
          command: yarn prisma migrate dev --skip-generate
      - run:
          name: Run test
          command: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; yarn test:normal --shard=${SHARD}/${CIRCLE_NODE_TOTAL} && yarn test:maintenance-mode --shard=${SHARD}/${CIRCLE_NODE_TOTAL}
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: screenshots
      - store_artifacts:
          path: playwrightOutput

      - persist_to_workspace: # cache stuff
          root: ~/project
          paths:
            - .
workflows:
  version: 2
  test:
    jobs:
      - run-test
