name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "yarn"
    - name: Cache node_modules
      uses: ./.github/composite-actions/cache-node-modules
    - name: Install dependencies
      shell: bash
      run: yarn ci
