name: gen-pwa
on:
  push:
    paths:
      - "public/favicon.svg"
jobs:
  update-icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: git config --global user.email "thomassiclark@gmail.com"
      - run: git config --global user.name "version bot"
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: yarn ci
      - run: yarn gen:pwa
        env:
          REDIS_CONNECTION_STRING: ${{ secrets.REDIS_CONNECTION_STRING }}
      - run: git add .
      - run: git commit -m "chore:update icons [AUTOMATED COMMIT]" --no-verify
        continue-on-error: true
        id: commit-step
      - run: git push
        if: ${{ steps.commit-step.outcome == 'success'}}
